version: '3.8'

services:
  asir_bind9:
    container_name: ASIR2
    # usamos esta imagen para poder ver los logs
    # la imagen de internetsystemsconsortium/bind9
    # no muestra los logs
    image: ubuntu/bind9
    # especificamos la plataforma de la imagen
    # es posible conflicto cuando el host es 'arm'
    # ya que no existe una imagen para esa plataforma
    platform: linux/amd64
    ports:
      - 54:53
    networks:
      bind9_subnet:
        ipv4_address: 172.28.5.1
    volumes:
      - ./conf:/etc/bind
      - ./zonas:/var/lib/bind
  cliente:
    container_name: N1cliente
    image: ubuntu
    platform: linux/amd64
    tty: true
    stdin_open: true
    # configuramos para que el cliente use nuestro dns
    dns:
      - 172.28.5.1
    networks:
      bind9_subnet:
        ipv4_address: 172.28.5.2
    
networks:
  bind9_subnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
          ip_range: 172.28.5.0/24
          gateway: 172.28.5.254
